import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(6,4),columns=list('ABCD'))
print(df)
print('-----------------1--------------------')
print(df['C'])
print('-----------------2--------------------')
print(df.loc[2])
print('-----------------3--------------------')
print(df.iloc[4])
print('-----------------4--------------------')
print(df.loc[2:3])
print('-----------------5--------------------')
print(df[1:3])
print('-----------------6--------------------')
print(df[1:3].T)  # 行专列
print('-----------------7--------------------')
print(df)
print('-----------------8--------------------')
print(df.sub(df.iloc[2], axis='columns'))
print('-----------------9--------------------')
print(df.sub(df['C'], axis='index'))
print('-----------------10--------------------')
print(df.loc[1, ['B', 'A']]) # 行列取值
print('-----------------11--------------------')
print(df)
print(df[::4])
print('-----------------12--------------------')
print(df.loc[:, df.loc[3] > 0])